name: PR Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # React용 Node.js 세팅
      - name: Setup Node.js (React)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontEnd

      - name: Run React Linter
        run: |
          npx eslint . --quiet
        working-directory: ./frontEnd

      # 🧪 Spring Boot 테스트 추가
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create TEST .env file
        run: |
          echo "DATABASE_URL=jdbc:oracle:thin:@54.180.159.162:1521:xe" > backEnd/.env
          echo "DATABASE_USERNAME=TEST" > backEnd/.env
          echo "DATABASE_PASSWORD=TEST" > backEnd/.env

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
        working-directory: ./backEnd

      - name: Run Spring Boot Tests
        run: ./gradlew test --info
        working-directory: ./backEnd
